


using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Goobstation.Silicons.AI.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AIModuleWindow : DefaultWindow
    {
        public event Action<string>? OnFreeformChanged;
        private bool _focused;
        private string _law = string.Empty;

        public AIModuleWindow()
        {
            RobustXamlLoader.Load(this);
            LawLineEdit.OnTextEntered += e =>
            {
                _law = e.Text;
                OnFreeformChanged?.Invoke(_law);
            };
        }

        public void SetCurrentLaw(string law)
        {
            if (law == _law)
                return;

            _law = law;
            if (!_focused)
                LawLineEdit.Text = law;
        }
    }
}